name: Build client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install meson ninja
        
    - name: build client
      run: ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: Executable
        path: ./client
    - uses: actions/upload-artifact@v3
      with:
        name: Static libraries
        path: lib*.a

