name: Build client

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install meson ninja

    - name: build client
      run: ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: Executable
        path: ./client
