name: Build client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install meson ninja

    - name: build client
      run: ./build.sh

    - name: Update Release
      uses: andelf/nightly-release@main
      if: github.repository == 'Xtr126/wayland-getevent'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        name: 'Release $$'
        prerelease: false
        body: |
          Initial release of the client binary.
          Based on ${{ github.sha }}
        files: |
          ./client

